language: smalltalk
sudo: false

# Select operating system(s)
os:
  - linux

# Select compatible Smalltalk image(s)
smalltalk:
  - Pharo-7.0
  - Pharo-6.0
  - Pharo-6.1
  - Pharo-5.0

allow_failures:
  - smalltalk: Pharo-7.0
  
